### PR TITLE
ffmpeg updated to v3.1 and resolved build errors in ffmpeginterop

### PR DESCRIPTION
**Pull request by helmut-steiner**
According to issue #80 - Build Error : FFmpeg 3.1v 
Incorporated fixes from dingpong

### CODE REVIEW

**Comment by khouzam** [comment]
Hi @helmut-steiner 

Thanks you very much for the contribution,

I'm taking a look at the code and there are few things that I'm looking at fixing before accepting the pull request, notably the coding style to stay in line with the rest of the project as well as the early returns, it looks as though the failures would result in some memory leaks.

Also, have you run the tests to validate that this doesn't introduce regressions?

Thanks.

**Comment by helmut-steiner** [comment]
Hm, looks like I just ran the streaming tests previously. The **CreateFromUri_Options** test throws an "Invalid FFmpeg option(s)" when running. All other tests pass. Big apologies for that!! I needed a quick fix for my app and as written incorporated the fixes from user dingpong. 
Gotta look into this...

Thanks for your response and the FFmpegInterop project in general!!

**Comment by helmut-steiner** [comment]
So I had a bit time and tracked down the error to the line
`if (avformat_open_input(&avFormatCtx, charStr, NULL, &avDict) < 0)` in
`FFmpegInteropMSS::CreateMediaStreamSource(String^ uri, bool forceAudioDecode, bool forceVideoDecode, PropertySet^ ffmpegOptions)` which fails to open the rtsp stream. Any ideas?

**Comment by khouzam** [comment]
Thanks a lot @helmut-steiner.

I'll validate, format the code and merge.

**Comment by khouzam** [comment]
@helmut-steiner,

I took a look at the code and there is one aspect that I'll want to address before merging this in.

The documentation for  `avcodec_send_packet` mentions the following:
`                  Unlike with older APIs, the packet is always fully consumed,
                  and if it contains multiple frames (e.g. some audio codecs),
                  will require you to call avcodec_receive_frame() multiple
                  times afterwards before you can send a new packet.
`

Therefore, I'd like to adapt the code to make sure to call `avcodec_receive_frame` to drain the decoded frames before the next call to `avcodec_send_packet`

**Comment by helmut-steiner** [comment]
Yes sure, please adapt it! Sorry for missing that!

**Comment by khouzam** [comment]
I've created a new branch, helmut-steiner-ffmpeg3.1, which has @helmut-steiner changes as well as the changes in logic for the new `avcodec_send_packet` and `avcodec_receive_frame` logic. I've tried it on a few files and things look good. According to the samples that we pull out of the file and the ones that we pull out of the decoder, everything matches up.

I need to do some more testing with a bigger variety of files, but I'd like to see if other can try it and see if they find any issues.

Thanks

**Comment by helmut-steiner** [comment]
Thank you!

**Pull request merged**
